"""create table chat

Revision ID: 98c2184b104e
Revises: 52c0628f5bfe
Create Date: 2024-12-12 23:17:39.016542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c2184b104e'
down_revision: Union[str, None] = '52c0628f5bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogs',
    sa.Column('user_1', sa.BigInteger(), nullable=False),
    sa.Column('user_2', sa.BigInteger(), nullable=False),
    sa.Column('messages', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_1'),
    sa.UniqueConstraint('user_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogs')
    # ### end Alembic commands ###
